### ISSUE TITLE
Click Item in Track Then Click Next

### ISSUE THREAD

**Issue by patrick-wirth** [oel-mediateam/audioplayer#4]
Hi Ethan, 

I experienced a bug today with the new audio player.  If I click on an item in a playlist and then click the next button, the player does not proceed to the proper track.  

Example: https://media.uwex.edu/content/hwm/hwm720_r18/hwm720_unit1/index.html

Scenario: 
- Open the presentation
- Click on track 5 of 9: METs and Metabolic Equivalents
- Click "next track" button

**Comment by Lin87** [comment]
Got it. First thing I’ll fix when I get back. Thanks!

**Comment by Lin87** [comment]
Fixed!
